import React from 'react';
import { LogIn, Zap, CheckCircle, Code, Shield, Key, Github, Linkedin } from 'lucide-react';

interface Feature {
    icon: React.ElementType;
    title: string;
    description: string;
}

interface Step {
    step: number;
    title: string;
    description: string;
    codeBlock?: string;
}

const features: Feature[] = [
    {
        icon: Zap,
        title: 'Automated Scanning',
        description: 'Integrate directly into your CI/CD pipeline. Automatically process scan results from tools like Trivy.',
    },
    {
        icon: Shield,
        title: 'AI-Powered Analysis',
        description: 'A LangGraph multi-agent system processes JSON scan results to provide in-depth analysis and context.',
    },
    {
        icon: CheckCircle,
        title: 'Clear Solutions',
        description: 'Stop guessing. Get clear, actionable solutions for every identified vulnerability and risk.',
    },
    {
        icon: Key,
        title: 'Secure API Access',
        description: 'Manage dedicated API keys for each project, ensuring secure and authenticated submission of scan data.',
    },
];

const steps: Step[] = [
    {
        step: 1,
        title: 'Sign Up & Create a Project',
        description: 'Register for an account and create a new project in the SecAI dashboard. This will generate a unique Project ID.',
    },
    {
        step: 2,
        title: 'Generate Your API Key',
        description: 'Inside your project settings, generate an API key with a desired validity (e.g., 30 days) for secure pipeline authentication.',
    },
    {
        step: 3,
        title: 'Integrate into Your CI/CD',
        description: 'Use the `curl` command in your pipeline (e.g., GitHub Actions) to send the JSON scan results (from Trivy, etc.) to your SecAI endpoint. ',
        codeBlock: `
            - name: Upload Scan Results to SecAI
              uses: Naveenchand06/secai-assistant/secai-action@v1.0.0
              with:
                  secai-url: <secrets.SECAI_URL>
                  project-id: <secrets.SECAI_PROJECT_ID>
                  api-key: <secrets.SECAI_PROJECT_API_KEY>
        `,
    },
    {
        step: 4,
        title: 'Review Intelligent Reports',
        description: 'Log back into SecAI to view the summary, risk analysis, and clear solutions generated by the AI for your latest scan result.',
    },
];

const LandingPage: React.FC = () => {
    const SECURE_COLOR = 'indigo-600';
    const SECURE_COLOR_LIGHT = 'indigo-500';

    return (
        <div className="min-h-screen bg-gray-50 font-sans">
            {/* Header */}
            <header className="sticky top-0 z-10 bg-white shadow-md">
                <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex justify-between items-center py-4">
                    <h1 className={`text-2xl font-bold text-${SECURE_COLOR}`}>
                        SecAI<span className="text-gray-900"> Assistant</span>
                    </h1>
                    <a
                        href="/login"
                        className={`flex items-center space-x-2 px-4 py-2 text-sm font-medium text-white bg-indigo-600 rounded-lg hover:bg-${SECURE_COLOR_LIGHT} transition duration-150`}
                    >
                        <LogIn size={18} />
                        <span>Login / Sign Up</span>
                    </a>
                </div>
            </header>

            <main>
                {/* Hero Section */}
                <section className={`bg-white pt-16 pb-20 shadow-inner`}>
                    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
                        <h2 className="text-5xl font-extrabold tracking-tight text-gray-900 sm:text-6xl">
                            Turn <span className={`text-${SECURE_COLOR}`}>Scan Noise</span> into <span className="text-green-600">Actionable Insights</span>.
                        </h2>
                        <p className="mt-6 text-xl text-gray-600 max-w-3xl mx-auto">
                            SecAI Assistant is your intelligent layer for CI/CD security. We process raw vulnerability scan data (like Trivy) and transform it into clear summaries, contextual risk analysis, and practical solutions using a multi-agent AI system.
                        </p>
                        <div className="mt-10 flex justify-center space-x-4">
                            <a
                                href="/register"
                                className={`inline-flex items-center justify-center px-8 py-3 border border-transparent text-base font-medium rounded-md shadow-lg text-white bg-indigo-700 hover:bg-indigo-600 transition duration-150`}
                            >
                                Get Started for Free
                            </a>
                            <a
                                href="#how-it-works"
                                className="inline-flex items-center justify-center px-8 py-3 border-2 border-indigo-200 text-base font-medium rounded-md text-indigo-700 bg-indigo-50 hover:bg-indigo-100 transition duration-150"
                            >
                                Learn More
                            </a>
                        </div>

                    </div>
                </section>

                {/* Features Section */}
                <section className="py-20 bg-gray-50">
                    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                        <div className="text-center">
                            <h3 className={`text-base font-semibold tracking-wide uppercase text-${SECURE_COLOR}`}>FEATURES</h3>
                            <p className="mt-2 text-3xl leading-8 font-extrabold tracking-tight text-gray-900 sm:text-4xl">
                                Intelligence for Your DevOps Pipeline
                            </p>
                        </div>

                        <div className="mt-16 grid gap-10 md:grid-cols-2 lg:grid-cols-4">
                            {features.map((feature, index) => (
                                <div key={index} className="flex flex-col items-center text-center p-6 bg-white rounded-xl shadow-lg hover:shadow-2xl transition duration-300 transform hover:-translate-y-1">
                                    <feature.icon className={`h-10 w-10 text-${SECURE_COLOR} mb-4`} />
                                    <h4 className="text-xl font-semibold text-gray-900">{feature.title}</h4>
                                    <p className="mt-2 text-base text-gray-500">{feature.description}</p>
                                </div>
                            ))}
                        </div>
                    </div>
                </section>

                {/* How It Works Section */}
                <section id="how-it-works" className={`py-20 bg-white`}>
                    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                        <div className="text-center">
                            <h3 className={`text-base font-semibold tracking-wide uppercase text-${SECURE_COLOR}`}>WORKFLOW</h3>
                            <p className="mt-2 text-3xl leading-8 font-extrabold tracking-tight text-gray-900 sm:text-4xl">
                                Simple 4-Step Integration
                            </p>
                        </div>

                        <div className="mt-16 relative">
                            {/* Vertical line connector */}
                            <div className={`hidden md:block absolute left-1/2 transform -translate-x-1/2 top-0 bottom-0 w-0.5 bg-${SECURE_COLOR_LIGHT}/50`}></div>

                            <div className="space-y-12">
                                {steps.map((step) => (
                                    <div key={step.step} className="relative flex flex-col md:flex-row items-start md:odd:flex-row-reverse">
                                        <div className="flex items-center justify-center md:absolute md:left-1/2 md:transform md:-translate-x-1/2 w-12 h-12 rounded-full border-4 border-white shadow-lg bg-white z-10 mx-auto md:mx-0">
                                            <span className={`text-xl font-bold text-${SECURE_COLOR}`}>{step.step}</span>
                                        </div>

                                        {/* Content Block */}
                                        <div className="w-full md:w-5/12 pt-4 md:pt-0">
                                            <div className={`p-6 bg-gray-50 rounded-lg shadow-md md:odd:text-left transition duration-300 hover:shadow-xl`}>
                                                <h4 className="text-xl font-bold text-gray-900 flex items-center md:odd:justify-start">
                                                    <Code className={`h-5 w-5 mr-2 text-${SECURE_COLOR} md:odd:order-2 md:odd:ml-2 md:odd:mr-0`} />
                                                    {step.title}
                                                </h4>
                                                <p className="mt-2 text-gray-600">{step.description}</p>
                                                {step.codeBlock && (
                                                    <div>
                                                        <pre className="mt-4 p-3 text-xs bg-gray-800 text-gray-100 rounded-md overflow-x-scroll">
                                                            <code>{step.codeBlock.trim()}</code>
                                                        </pre>
                                                    </div>
                                                )}
                                            </div>
                                        </div>

                                        <div className="hidden md:block w-2/12"></div>
                                    </div>
                                ))}
                            </div>
                        </div>
                    </div>
                </section>

                {/* CTA Section */}
                <section className={`bg-grey-200 py-16 border-top`}>
                    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
                        <h3 className="text-3xl font-extrabold text-indigo-600 sm:text-4xl">
                            Ready to See Smarter Security Reports?
                        </h3>
                        <p className="mt-4 text-xl text-black-200">
                            Integrate SecAI in minutes and start understanding your vulnerabilities better today.
                        </p>
                        <div className="mt-8">
                            <a
                                href="/register"
                                className={`inline-flex items-center justify-center px-8 py-3 border border-transparent text-base font-medium rounded-md shadow-lg text-${SECURE_COLOR} bg-white hover:bg-gray-50 transition duration-150`}
                            >
                                Start Your Free Account
                            </a>
                        </div>
                    </div>
                </section>
            </main>

            {/* Footer */}
            <footer className="bg-gray-800 py-8">
                <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center text-gray-400">
                    <p>&copy; {new Date().getFullYear()} SecAI Assistant. All rights reserved.</p>

                    <div className="mt-4 pt-4 border-t border-gray-700">
                        <p className="text-sm text-gray-400">
                            Developed by{" "}
                            <span className="font-semibold">
                                <a
                                    href="https://bio.link/Naveenchand"
                                    target="_blank"
                                    className="text-green-400 hover:text-indigo-400 transition-colors"
                                >
                                    Naveenchand
                                </a>
                            </span>
                        </p>
                        <div className="flex justify-center space-x-4 mt-2">
                            <a
                                href="https://github.com/Naveenchand06/"
                                target="_blank"
                                rel="noopener noreferrer"
                                className="text-gray-400 hover:text-white transition duration-150"
                                aria-label="Naveenchand's GitHub"
                            >
                                <Github size={20} />
                            </a>
                            <a
                                href="https://www.linkedin.com/in/naveenchand06/"
                                target="_blank"
                                rel="noopener noreferrer"
                                className="text-gray-400 hover:text-white transition duration-150"
                                aria-label="Naveenchand's LinkedIn"
                            >
                                <Linkedin size={20} />
                            </a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    );
};

export default LandingPage;